name: Access Local Service via Cloudflare Tunnel

# workflow_dispatch 表示手动触发
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  cloudflare-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Setup cloudflared tunnel
        uses: AnimMouse/setup-cloudflared/tunnel@v2
        with:
          cloudflare_tunnel_credential: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIAL }}
          cloudflare_tunnel_configuration: ${{ vars.CLOUDFLARE_TUNNEL_CONFIGURATION }}
          cloudflare_tunnel_id: ${{ vars.CLOUDFLARE_TUNNEL_ID }}

      - name: Wait for tunnel to stabilize
        run: sleep 10

      - name: Call Drone API via Cloudflare Tunnel
        run: |
          curl --location --request POST 'http://github.riji.life/api/repos/DevOps/action-sync-images/builds?branch=main' \
            --header 'Authorization: Bearer ${{ secrets.DRONE_API_TOKEN }}' \
            --header 'User-Agent: GitHubAction/1.0' \
            --header 'Accept: */*' \
            --header 'Host: github.riji.life' \
            --header 'Connection: keep-alive' \
            -v
